// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4kE7fXpm4xAkmCg4zXQeOwjtQKC1Fd8E',
    appId: '1:1079443073222:web:0c309afa5bed3abf0ecfc7',
    messagingSenderId: '1079443073222',
    projectId: 'unitask-app',
    authDomain: 'unitask-app.firebaseapp.com',
    storageBucket: 'unitask-app.firebasestorage.app',
    measurementId: 'G-WWHC1B1B47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD72Oo1-g2UX99L9pkWoCuTotMbNQ8Qpxo',
    appId: '1:1079443073222:android:29165cd1145570b70ecfc7',
    messagingSenderId: '1079443073222',
    projectId: 'unitask-app',
    storageBucket: 'unitask-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC17XYpVEPx26ZCyNaV98_iFsiMOwIDR8w',
    appId: '1:1079443073222:ios:cb433d7737ca2c0a0ecfc7',
    messagingSenderId: '1079443073222',
    projectId: 'unitask-app',
    storageBucket: 'unitask-app.firebasestorage.app',
    iosClientId: '1079443073222-lm2hos6cftlisrj96k5gpsq6p6odk0m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitaskFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC17XYpVEPx26ZCyNaV98_iFsiMOwIDR8w',
    appId: '1:1079443073222:ios:cb433d7737ca2c0a0ecfc7',
    messagingSenderId: '1079443073222',
    projectId: 'unitask-app',
    storageBucket: 'unitask-app.firebasestorage.app',
    iosClientId: '1079443073222-lm2hos6cftlisrj96k5gpsq6p6odk0m1.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitaskFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4kE7fXpm4xAkmCg4zXQeOwjtQKC1Fd8E',
    appId: '1:1079443073222:web:115297e528e2b90e0ecfc7',
    messagingSenderId: '1079443073222',
    projectId: 'unitask-app',
    authDomain: 'unitask-app.firebaseapp.com',
    storageBucket: 'unitask-app.firebasestorage.app',
    measurementId: 'G-4115VNHPR3',
  );
}
